### ISSUE TITLE
Website Design issues,

### ISSUE THREAD

**Issue by HishamAbualhaj** [PL-FAC-1/hinda-task2#9]
- let the content breathe:
	- give each icon more padding from left-right so they will be like a circule.
	- add some line-height to paragraph, adjust the size of it.
	- Dont use button tag,as you will spend more them trying to restyle it ,you could've used div and a, easy to style.
 - wrap all content in one container, 
 - overflow issue comes from the width of the consection5, line 207 css , assigning width of 100vw doesn't bring any benefit:

 
```css
.consection5 {
    height: 90vh;
    width: 100vw; // issue here
    display: flex;
    flex-direction: row;
    justify-content: center;
    background-color: rgb(228, 229, 231);
}
```

**Comment by Hinda-sh** [comment]
https://github.com/PL-FAC-1/hinda-task2.git

**Comment by HishamAbualhaj** [comment]
```css
// use this for button styling, if you want to change the style of one btn, change it with parent name 
/* example: footer .btn {
border-color:white;
}*/
.btn {
  width: fit-content;
  font-weight: 100;
  border: 1px solid rgba(0, 0, 0, 0.6);
  padding: 15px 45px;
  border-radius: 35px;
  letter-spacing: 2px;
  text-transform: uppercase;
  font-size: 14px;
  transition: 0.3s;
}
.btn:hover {
  background-color: rgba(0, 0, 0, 0.6);
  border-color: rgba(0, 0, 0, 0.6);
  color: white;
}
```
